language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - find -type d -name vendor -prune -o -type f -name '*.php' -print0 | xargs -0 -n 1 php -l
  - ./vendor/bin/phpcs -p --standard=PSR2 --extensions=php src tests
  - ./vendor/bin/phpmd src text controversial,design,naming
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover